# Generated by Django 4.2.8 on 2024-01-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_permissoes',
            field=models.BooleanField(default=False, verbose_name='Permissao de Postagem'),
        ),
    ]
