# Generated by Django 4.2.8 on 2024-01-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refeicao_permissoes',
            field=models.BooleanField(default=False, verbose_name='Permissao de Refeicao'),
        ),
    ]
