import type { Metadata } from 'next'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from './components/Footer'
import { Inria_Serif, Inter } from 'next/font/google';
import { config } from "@fortawesome/fontawesome-svg-core";
// Tell Font Awesome to skip adding the CSS automatically 
// since it's already imported above
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })
// const inria_serif = Inria_Serif({ weight: "700", subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'Página Inicial',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" data-theme="light">
      <body className={inter.className}>{children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
