# Generated by Django 4.2.8 on 2024-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Refeicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_refeicao",
                    models.CharField(
                        choices=[
                            ("N", "Normal"),
                            ("V", "Vegetariana"),
                            ("A", "Acompanhamento"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "nome_refeicao",
                    models.CharField(max_length=255, verbose_name="Nome"),
                ),
                ("data", models.DateField(verbose_name="Data")),
            ],
            options={
                "verbose_name": "Refeicao",
                "verbose_name_plural": "Refeicoes",
                "ordering": ["data"],
            },
        ),
    ]
