# Generated by Django 4.2.8 on 2024-01-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refeicao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refeicao",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
