# Generated by Django 4.2.8 on 2024-01-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("refeicao", "0004_alimentoadicional_rename_refeicao_alimento_cardapio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alimento",
            options={
                "ordering": ["id"],
                "verbose_name": "Alimento",
                "verbose_name_plural": "Alimentos",
            },
        ),
        migrations.CreateModel(
            name="CardapioAlimentoAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "alimento_adicional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="refeicao.alimentoadicional",
                    ),
                ),
                (
                    "cardapio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="refeicao.cardapio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cardapio",
            name="alimentos_adicionais",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="cardapios",
                to="refeicao.cardapioalimentoadicional",
            ),
        ),
    ]
