# Generated by Django 4.2.8 on 2024-01-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refeicao", "0005_alter_alimento_options_cardapioalimentoadicional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardapio",
            name="alimentos_adicionais",
            field=models.ManyToManyField(
                blank=True,
                related_name="cardapios",
                to="refeicao.cardapioalimentoadicional",
            ),
        ),
    ]
