# Generated by Django 4.2.8 on 2024-01-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0007_alter_cardapio_alimentos_adicionais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='alimentos_adicionais',
        ),
        migrations.DeleteModel(
            name='AlimentoAdicional',
        ),
    ]
