# Generated by Django 4.2.8 on 2024-01-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0008_remove_cardapio_alimentos_adicionais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cadarpio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_adicionais', to='refeicao.cardapio')),
            ],
            options={
                'verbose_name': 'Alimento Adicional',
                'verbose_name_plural': 'Alimentos Adicionais',
                'ordering': ['nome'],
            },
        ),
    ]
