# Generated by Django 4.2.8 on 2024-01-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0009_alimentoadicional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentoAdicional',
        ),
    ]
