# Generated by Django 5.0 on 2023-12-11 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorito_post",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorito",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favorito",
            ),
        ),
    ]
