# Generated by Django 4.2.8 on 2024-01-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("setores", "0001_initial"),
        ("posts", "0002_remove_post_favorito_post_favorito"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imagem_post",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_img/%Y/%m/%d",
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="setor_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts",
                to="setores.setor",
                verbose_name="Setor",
            ),
        ),
    ]
